Cancels packaging if there is an HTTP error during downloads

diff --git a/lib/packager b/lib/packager
--- a/lib/packager
+++ b/lib/packager
@@ -77,10 +77,16 @@ function __translate_url_to_filename {
 
 
 function __download_dependency {
-    filename=$(__translate_url_to_filename $1)
+    url=$1
+    filename=$(__translate_url_to_filename $url)
 
     if [ "$cache" == false ] || [ ! -f ${cache_directory}/${filename} ]; then
-        curl $1 -o ${cache_directory}/${filename} -L
+        curl $url -o ${cache_directory}/${filename} -L --fail
+
+        if [ "$?" -ne "0" ] ; then
+            echo "Cancelled packaging because of HTTP error when fetching ${url}"
+            exit 1
+        fi
     fi
 
     cp "${cache_directory}/${filename}" ./dependencies
